name: Download test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Poopizer
        shell: pwsh
        run: Install-Module -Name PowerPoopizer -Force 
      - name: Poop
        shell: pwsh
        run: Get-PoopsFromString -Src "Poop"
      - name: Override
        shell: pwsh
        run: Get-PoopsFromString -Src "Poop" -OverridePoop "💰"
